# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20161013_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='logo',
        ),
        migrations.AddField(
            model_name='location',
            name='location_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(max_length=555),
        ),
        migrations.AlterField(
            model_name='location',
            name='logo_up',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='location',
            name='menu',
            field=models.FilePathField(blank=True, null=True, path='uploads/menus'),
        ),
        migrations.AlterField(
            model_name='location',
            name='menu_up',
            field=models.FileField(blank=True, null=True, upload_to='uploads/menus'),
        ),
    ]
